@baseUrl = http://localhost:3000

# @name createEvent
POST {{baseUrl}}/events
Content-Type: application/json

{
    "name": "Global Tech Summit 2026",
    "startTime": "2026-03-09T08:00:00Z",
    "endTime": "2026-03-10T20:00:00Z",
    "status": "ACTIVE",
    "window": 480
}

###

# @name findAllEvents
GET {{baseUrl}}/events

###

# @name findActiveEvents
GET {{baseUrl}}/events/active

###

# @name findOneEvent
@eventId = replace-with-uuid
GET {{baseUrl}}/events/{{eventId}}

###

# @name updateEvent
@eventIdToUpdate = replace-with-uuid
PATCH {{baseUrl}}/events/{{eventIdToUpdate}}
Content-Type: application/json

{
    "name": "Updated Tech Summit 2026",
    "status": "COMPLETED"
}

###

# @name removeEvent
@eventIdToDelete = replace-with-uuid
DELETE {{baseUrl}}/events/{{eventIdToDelete}}
