@baseUrl = http://localhost:3000

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Operator Joe",
    "email": "joe@example.com",
    "password": "simplepassword",
    "role": "OPERATOR"
}

###

# @name findAllUsers
GET {{baseUrl}}/users

###

# @name findOneUser
@userId = replace-with-uuid
GET {{baseUrl}}/users/{{userId}}

###

# @name updateUser
@userIdToUpdate = replace-with-uuid
PATCH {{baseUrl}}/users/{{userIdToUpdate}}
Content-Type: application/json

{
    "name": "Updated Joe",
    "role": "MANAGER",
    "isActive": true
}

###

# @name assignPermissions
@userIdForPermissions = replace-with-uuid
POST {{baseUrl}}/users/{{userIdForPermissions}}/permissions
Content-Type: application/json

{
    "permissions": ["VIEW_REPORTS", "MANAGE_VIPS"]
}

###

# @name revokePermission
@permissionId = replace-with-uuid
DELETE {{baseUrl}}/users/permissions/{{permissionId}}

###

# @name removeUser
@userIdToDelete = replace-with-uuid
DELETE {{baseUrl}}/users/{{userIdToDelete}}
