@baseUrl = http://localhost:3000

# @name createVip
POST {{baseUrl}}/vip
Content-Type: application/json

{
    "plate": "ABC 123",
    "name": "John Doe"
}

###

# @name listVips
GET {{baseUrl}}/vip

###

# @name listVipsByPlate
GET {{baseUrl}}/vip?plate=ABC
