export enum RealtimeEvent {
    ALERT_CREATED = 'ALERT_CREATED',
    VIP_ARRIVED = 'VIP_ARRIVED',
    VIP_ADDED = 'VIP_ADDED',
    VIP_CONFIRMED = 'VIP_CONFIRMED',
    VIP_COMPLETED = 'VIP_COMPLETED',
    CAMERA_HEALTH = 'CAMERA_HEALTH',
    VIP_STATUS_CHANGED = 'VIP_STATUS_CHANGED',
    VIP_REJECTED = 'VIP_REJECTED',
}

export enum RealtimeConfig {
    MAX_CONNECTIONS = 5,
    TICKET_TTL_MS = 60000,
    HEARTBEAT_INTERVAL_MS = 30000,
}
